version: '2.1'
services:
  # postgres:
  #   image: postgres:9.5
  #   ports:
  #    - "5433:5432"
  # oracle:
  #   image: wnameless/oracle-xe-11g
  #   ports:
  #    - "1521:1521"
  appsvr:
    # image: 38leinad/wildfly-10-jdbc
    image: openjdk:8
    # Add "wait-for db:1521 -- <command>" to command to wait on another service.
    command: ["java", "-jar", "/opt/carz.jar"]
    ports:
     - "80:8080"
    volumes:
     - "./target/carz.jar:/opt/carz.jar"
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
