version: '2.1'
services:
  postgres:
    image: postgres:9.5
    ports:
     - "5432:5432"
  appsvr:
    image: payara/server-full:5-SNAPSHOT
    ports:
     - "8080:8080"
    volumes:
     - "./build/libs/cars.war:/opt/payara5/glassfish/domains/domain1/autodeploy/cars.war"
    environment:
      - "DB_SERVERNAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_DATABASENAME=postgres"